#!/usr/bin/env bash

# get bash colors and styles here: 
# http://misc.flogisoft.com/bash/tip_colors_and_formatting
C_RESET='\e[0m'
C_RED='\e[31m'
C_GREEN='\e[32m'
C_YELLOW='\e[33m'

files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$')


function __run() #(step, name, cmd)
{
    local color output exitcode

    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"

	if [[ "$3" == *"PHP Cs Fixer"* ]]; then
		for file in $files; do
			php vendor/bin/pint $file --quiet
		done
	else
		output=$(eval "$3" 2>&1)
	fi

    exitcode=$?

    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
        echo -e "${C_GREEN}OK!${C_RESET}"
    else
        echo -e "${C_RED}NOK!${C_RESET}\n\n$output"
        exit 1
    fi
}

modified="git diff --diff-filter=M --name-only --cached  | grep \".php$\""
ignore="resources/lang,resources/views,bootstrap/helpers,database/migrations,bin"
phpcs="php vendor/bin/pint app --quiet"

__run "1/2" "Laravel Pint" "${phpcs}"
__run "2/2" "Laravel STAN" "${modified} | xargs -r vendor/bin/phpstan analyse"


for file in $files; do
	git add $file
done
